name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: juliopdx/exabgp-irt
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest, $(date +%F)

      - name: sync desc and readme
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{secrets.DOCKER_USER }}
          pass: ${{ secrets.DOCKER_PASSWORD }}
