name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image and push
        run: |
          docker build . --file Dockerfile --tag juliopdx/exabgp-irt:$(date +%s)
          docker push juliopdx/exabgp-irt:$(date +%s)

      - name: sync desc and readme
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{secrets.DOCKER_USER }}
          pass: ${{ secrets.DOCKER_PASSWORD }}
